services:
    db:
        container_name: 'db'
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'Admin123'
            MYSQL_DATABASE: 'ql'
        volumes:
            - datavolume:/var/lib/mysql
        ports:
            - '3306:3306'
    nextapp:
        container_name: nextapp
        build:
            context: ./internal/web/
            dockerfile: ../../docker/nextapp/Dockerfile
        env_file: './internal/web/.production.env'
        depends_on:
            - goapi
        ports:
            - '3000:3000'
    goapi:
        container_name: goapi
        build:
            context: .
            dockerfile: ./docker/goapi/Dockerfile
        env_file: './.production.env'
        volumes:
            - filevolume:/public
            - logfilevolume:/log
        depends_on:
            - db
        ports:
            - 8080:8080
volumes:
    datavolume:
    filevolume:
    logfilevolume:
